# ---------------------------------------------------------------------------------------------------
# Examples:
#   - Open bash inside container (CAETÊ folder). Use this command to run any command mannualy:
#       docker compose run caete-bash
#   - Compile and run CAETÊ with interactive arguments:
#       docker compose run caete-run
#   - Compile and run CAETÊ without interactive arguments:
#     - Local:
#         PLS=1000 MASK=a VERSION=1 SOMBRERO=n OUTPUT_NAME=test ZONE=c docker compose run caete-run
#     - Sombrero:
#         PLS=1000 MASK=a VERSION=1 SOMBRERO=y CLIMATOLOGY=5 docker compose run caete-run
# ---------------------------------------------------------------------------------------------------

services:
  caete-base: &caete-base
    build:
      context: .
      dockerfile: Dockerfile
    image: caete:latest
    volumes:
      - .:/caete:rw
    stdin_open: true
    tty: true
    pull_policy: build

  caete-bash:
    <<: *caete-base
    command: bash -c "cd /caete/ && bash"

  caete-run:
    <<: *caete-base
    environment:
      - PLS=${PLS}
      - MASK=${MASK}
      - VERSION=${VERSION}
      - SOMBRERO=${SOMBRERO}
      - CLIMATOLOGY=${CLIMATOLOGY}
      - OUTPUT_NAME=${OUTPUT_NAME}
      - ZONE=${ZONE}
    command:
      - bash
      - -c
      - |
        set -euo pipefail &&
        cd /caete/src &&
        #### make clean &&
        if [ -n "${PLS:-}" ] && [ -n "${MASK:-}" ] && [ -n "${VERSION:-}" ] && [ -n "${SOMBRERO:-}" ]; then
          echo -e '\n=================\n Compiling CAETE\n=================\n' &&
          echo "$PLS" | make so
          echo -e '\n\n===============\n Running CAETE\n===============\n' &&
          if [ "$SOMBRERO" = "y" ]; then
            printf "%s\n%s\n%s\n%s\n%s" "$MASK" "$VERSION" "$SOMBRERO" "$CLIMATOLOGY" | python model_driver.py
          elif [ "${SOMBRERO:-}" = "n" ]; then
            printf "%s\n%s\n%s\n%s\n%s" "$MASK" "$VERSION" "$SOMBRERO" "$OUTPUT_NAME" "$ZONE" | python model_driver.py
          else
            echo "ERROR: SOMBRERO var value must be (y/n)"
            exit
          fi
        else
          echo -e '\n=================\n Compiling CAETE\n=================\n' &&
          make so
          echo -e '\n\n===============\n Running CAETE\n===============\n' &&
          python model_driver.py
        fi

